# Generated by Django 4.1.9 on 2023-06-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'get_latest_by': 'created_on'},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
