# Generated by Django 4.1.9 on 2023-06-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cart_created_by_alter_cart_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='carts',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_items',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
